config/routes.rb
Rails.application.routes.draw do
  resources :notes

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
	validates :title, presence: true,
						length: { minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def index
		@notes = Note.all
	end
	def show
		@note = Note.find(params[:id])
	end 

	def new
		@note = Note.new
	end

	def edit
		@note = Note.find(params[:id])
	end

	def create
		@note = Note.new(note_params)

		if @note.save
			redirect_to @note
		else
			render 'new'
		end
	end

	def update 
		@note = Note.find(params[:id])

		if @note.update(note_params)
			redirect_to @note
		else
			render 'edit'
		end
	end
	def destroy
		@note = Note.find(params[:id])
		@note.destroy

		redirect_to notes_path
	end

	private
		def note_params
			params.require(:note).permit(:title, :text)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trello</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h1>Editing note</h1>
 
<%= form_for :note, url: note_path(@note), method: :patch do |f| %>
 
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
<button> 
<%= link_to 'Back', notes_path %>
</button>

app/views/notes/index.html.erb
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Sortable - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <style>
  #sortable { list-style-type: none; margin: 0; padding: 0; width: 60%; }
  #sortable li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }
  #sortable li span { position: absolute; margin-left: -1.3em; }
  </style>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#sortable" ).sortable();
    $( "#sortable" ).disableSelection();
  } );
  </script>
  <style>
  #draggable { width: 100px; height: 100px; padding: 0.5em; float: left; margin: 10px 10px 10px 0; }
  #droppable { width: 150px; height: 150px; padding: 0.5em; float: left; margin: 10px; }
  </style>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#draggable" ).draggable();
    $( "#droppable" ).droppable({
      drop: function( event, ui ) {
        $( this )
          .addClass( "ui-state-highlight" )
          .find( "p" )
            .html( "Dropped!" );
      }
    });
  } );
  </script>
</head>

<body>
<h1>Trello Notes</h1>

<div id="center">
<%=link_to 'New note', new_note_path%>
</div>

<div id="dragggable">
 <div id="sortable" id="center">
  <% @notes.each do |note| %>
    <div class="panel panel-default" id="<%= note.id %>">
      <div class="panel-body">
        <p id=sticky id=center>
      <td><%= note.title %></td>
      <br>
      <td><%= note.text %></td>
      <br>
      <td><%= link_to 'Edit', edit_note_path(note) %></td>
      <td><%= link_to 'Destroy', note_path(note),
                method: :delete,
                data: { confirm: 'Is that a good idea?' } %></td>
      <br>
      </p>
  </div> 
  </div>


   

 
</body>
</html>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<div id=center>
<%= form_for :note, url: notes_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= form_for :note, url: notes_path do|f| %>

<% end %>

<%=link_to 'Back', notes_path%>
</div>

app/views/notes/show.html.erb
<p>
  <strong>Trello Note:</strong>
  <%= @note.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>



<%= link_to 'Edit', edit_note_path(@note) %>  |
<%= link_to 'Back', notes_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Fake Trello</h1>
<%= link_to 'My blog', controller: 'notes' %>